### ISSUE TITLE
About imagenet hyperparameters.

### ISSUE THREAD

**Issue by dongjunhwang** [ejkim47/bridging-gap-wsol#1]
great work. Thank you for sharing this awesome code.

I have a little question about the imagenet hyperparameters.

In the `Sensitivity to hyperparameters` section of appendix, hyperparameters of imagenet VGG16 exist, but not in resnet50.  
Also, epoch and warm epoch of imagenet are not exist in the paper.

I want to request about the imagenet yml file for resnet and vgg for training.

Thanks.

**Comment by ejkim47** [comment]
The hyperparameters for the ImageNet dataset are as follws.
Others are included in paper or same as the setting on the CUB dataset.

**VGG16**
epochs: 40
warm_epochs: 5
batch_size: 32
lr: 0.00002
lr_decay_rate: 0.1
lr_decay_points: [11, 31]
lr_classifier_ratio: 5.0

**ResNet50**
epochs: 30
warm_epochs: 14
batch_size: 32
lr: 0.00001
lr_decay_rate: 0.1
lr_decay_points: [21, 31]
lr_classifier_ratio: 10.0
loss_ratio_sim: 8.0
sim_fg_thres: 0.28
sim_bg_thres: 0.25
loss_ratio_norm: 1.0
loss_ratio_drop: 2.0
drop_threshold: 0.8
drop_prob: 0.25

Thank you:)
