### ISSUE TITLE
About Evaluation Metrics.

### ISSUE THREAD

**Issue by 893018991** [ejkim47/bridging-gap-wsol#3]
Thank you for sharing this awesome code.

I have a little question about  Evaluation Metrics.

![图片](https://user-images.githubusercontent.com/35445113/237035488-397c69ec-8d5b-4f32-b80b-c0b60ed807d1.png)

This is the result of running your code.

I want to konw which is Top-1 Loc,Top-5 Loc, and GT Loc ，Can you explain it to me?
Thank you.

**Comment by ejkim47** [comment]
Thank you for looking into my code!

This code only include MaxBoxAccV2 evaluation, not showing Top-k Loc and GT-Loc.
(loc_IOU_50 can be considered as general GT-Loc.)

Thank you.

**Comment by 893018991** [comment]
OK,Thank you for answering my question.
