### ISSUE TITLE
TypeError: round(): argument 'input' (position 1) must be Tensor, not int

### ISSUE THREAD

**Issue by CapricornGuang** [ejkim47/bridging-gap-wsol#4]
Within the data preprocessing function, `get_data_loader`, I found that the _transforms.ToTensor()_ operation should be placed before RandomCrop, or the TypeError problem will be raised

=============================
train=transforms.Compose([
            transforms.Resize((resize_size, resize_size)),
            transforms.ToTensor(),
            transforms.RandomCrop(crop_size),
            transforms.RandomHorizontalFlip(),
            transforms.Normalize(_IMAGE_MEAN_VALUE, _IMAGE_STD_VALUE)
        ])

**Comment by ejkim47** [comment]
Thank you for your interest in my code!

Upon reviewing the code that is currently shared, I did not encounter the type error you mentioned. The order you referred to seems fine to me. Could you please double-check it again?

Thank you:)
