### ISSUE TITLE
How to evaluate Top-1, Top-5, GT Loc Metric with these Code ?

### ISSUE THREAD

**Issue by CapricornGuang** [ejkim47/bridging-gap-wsol#5]
I am interested in your work. But after reading the repositories, I found myself fuzzy with how to reproduce the results of Top-1, Top-5, and GT-Loc announced in the paper. Can you provide me with the clue?

**Comment by ejkim47** [comment]
Thank you for your interest in my code!

This code only include MaxBoxAccV2 evaluation.
You can add various evaluation metrics in the following function. 
https://github.com/ejkim47/bridging-gap-wsol/blob/4561dc88bca1eb9789804a4b48f66c455016edde/trainer.py#L112-L125

You can incorporate Top-k Loc and GT-Loc code from other WSOL works or enhance our code by adding a section for evaluating classification accuracy using MaxBoxAccV2, as well.

Thank you.

**Comment by CapricornGuang** [comment]
Thanks for your timely reply, but the&nbsp;Top-k Loc and GT-Loc&nbsp;metrics have been inclueded in the article.&nbsp;
So how can i reproduce these metric's result ? Or the version that can be used to calculate these metrics have not be uploaded ?



Yuguang&nbsp;Yang
***@***.***







                       
Original
                       
                     

From:"ejkim47"< ***@***.*** &gt;;

Date:2023/10/13 13:41

To:"ejkim47/bridging-gap-wsol"< ***@***.*** &gt;;

CC:"Yuguang Yang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ejkim47/bridging-gap-wsol] How to evaluate Top-1, Top-5, GT LocMetric with these Code ? (Issue #5)




 
Thank you for your interest in my code!
 
This code only include MaxBoxAccV2 evaluation.
 You can add various evaluation metrics in the following function.
 https://github.com/ejkim47/bridging-gap-wsol/blob/4561dc88bca1eb9789804a4b48f66c455016edde/trainer.py#L112-L125
 
You can incorporate Top-k Loc and GT-Loc code from other WSOL works or enhance our code by adding a section for evaluating classification accuracy using MaxBoxAccV2, as well.
 
Thank you.
