### ISSUE TITLE
Reproduce the results (top-k Loc and GT-Loc)

### ISSUE THREAD

**Issue by CapricornGuang** [ejkim47/bridging-gap-wsol#6]
Thanks for your timely reply, but the&nbsp;Top-k Loc and GT-Loc&nbsp;metrics have been inclueded in the article.&nbsp;
So how can i reproduce these metric's result ? Or the version that can be used to calculate these metrics have not be uploaded ?

Yuguang&nbsp;Yang
***@***.***

Original

From:"ejkim47"< ***@***.*** &gt;;

Date:2023/10/13 13:41

To:"ejkim47/bridging-gap-wsol"< ***@***.*** &gt;;

CC:"Yuguang Yang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ejkim47/bridging-gap-wsol] How to evaluate Top-1, Top-5, GT LocMetric with these Code ? (Issue [#5](https://github.com/ejkim47/bridging-gap-wsol/issues/5))

Thank you for your interest in my code!

This code only include MaxBoxAccV2 evaluation.
 You can add various evaluation metrics in the following function.
 https://github.com/ejkim47/bridging-gap-wsol/blob/4561dc88bca1eb9789804a4b48f66c455016edde/trainer.py#L112-L125

You can incorporate Top-k Loc and GT-Loc code from other WSOL works or enhance our code by adding a section for evaluating classification accuracy using MaxBoxAccV2, as well.

Thank you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by ejkim47** [comment]
As you mentioned, this code exclusively incorporates MaxBoxAccV2 evaluation and does not include the Top-k Loc and GT-Loc.

**Comment by CapricornGuang** [comment]
Can you offer me some help about sharing the GitHub repository or Code you used for calculating these two metrics? Thanks very very very very very very very very very very very very very very very much !




123321123456
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "ejkim47/bridging-gap-wsol"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Oct 13, 2023 03:21 PM
***@***.***&gt;;
Cc:&nbsp;"Yuguang ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [ejkim47/bridging-gap-wsol] Reproduce the results (top-k Loc and GT-Loc) (Issue #6)





 
As you mentioned, this code exclusively incorporates MaxBoxAccV2 evaluation and does not include the Top-k Loc and GT-Loc.

**Comment by ejkim47** [comment]
have no plans to add those metrics to this repository. However, there are several publicly available codes that include those metrics.

The following repositories are examples of publicly released codes that include them:
https://github.com/won-bae/rethinkingCAM
https://github.com/Panxjia/SPA_CVPR2021/tree/main

Thank you for your understanding and consideration. :)

**Comment by CapricornGuang** [comment]
Thanks&nbsp;very&nbsp;very&nbsp;very&nbsp;very&nbsp;very&nbsp;very&nbsp;very much&nbsp;



Yuguang&nbsp;Yang
***@***.***







                       
Original
                       
                     

From:"ejkim47"< ***@***.*** &gt;;

Date:2023/10/13 15:36

To:"ejkim47/bridging-gap-wsol"< ***@***.*** &gt;;

CC:"Yuguang Yang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ejkim47/bridging-gap-wsol] Reproduce the results (top-k Loc andGT-Loc) (Issue #6)




 
have no plans to add those metrics to this repository. However, there are several publicly available codes that include those metrics.
 
The following repositories are examples of publicly released codes that include them:
 https://github.com/won-bae/rethinkingCAM
 https://github.com/Panxjia/SPA_CVPR2021/tree/main
 
Thank you for your understanding and consideration. :)

**Comment by CapricornGuang** [comment]
God well always bless you !!



Yuguang&nbsp;Yang
***@***.***







                       
Original
                       
                     

From:"ejkim47"< ***@***.*** &gt;;

Date:2023/10/13 15:36

To:"ejkim47/bridging-gap-wsol"< ***@***.*** &gt;;

CC:"Yuguang Yang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ejkim47/bridging-gap-wsol] Reproduce the results (top-k Loc andGT-Loc) (Issue #6)




 
have no plans to add those metrics to this repository. However, there are several publicly available codes that include those metrics.
 
The following repositories are examples of publicly released codes that include them:
 https://github.com/won-bae/rethinkingCAM
 https://github.com/Panxjia/SPA_CVPR2021/tree/main
 
Thank you for your understanding and consideration. :)
